import React from 'react';


const MethodologyPage = () => {
    return (
        <div className="min-h-screen bg-[#0A192F] text-gray-300 font-sans selection:bg-cyan-500 selection:text-white">
            {/* Navigation */}


            <main className="pt-12 max-w-4xl mx-auto px-6">
                <h1 className="text-4xl md:text-5xl font-bold text-white mb-8">
                    Methodology & Evidence Integrity
                </h1>

                <p className="text-xl text-gray-400 mb-12 leading-relaxed">
                    ChainForensix employs a deterministic, three-stage process to Capture, Analyze, and Preserve digital evidence from social media platforms, specifically X (formerly Twitter). Our workflow ensures data immutability and establishes a verifiable chain of custody.
                </p>

                <section className="mb-16">
                    <h2 className="text-2xl font-semibold text-white mb-4 border-l-4 border-cyan-500 pl-4">
                        1. High-Velocity Extraction
                    </h2>
                    <p className="mb-4">
                        We utilize specialized scrapers to capture the raw JSON payload of X posts directly from the platform's internal API. This ensures we collect metadata often hidden from the public UI, including:
                    </p>
                    <ul className="list-disc ml-6 space-y-2 text-gray-400">
                        <li>Exact UTC creation timestamp (down to the millisecond).</li>
                        <li>Original Device ID / Client Application.</li>
                        <li>Unmodified media URLs and attachment metadata.</li>
                        <li>Edit history flags.</li>
                    </ul>
                </section>

                <section className="mb-16">
                    <h2 className="text-2xl font-semibold text-white mb-4 border-l-4 border-cyan-500 pl-4">
                        2. AI-Powered Analysis
                    </h2>
                    <p className="mb-4">
                        Extracted text content is run through our proprietary fine-tuned AI model specifically designed for <strong>Defamation and Hate Speech Detection</strong>.
                    </p>
                    <div className="bg-gray-900 p-6 rounded-lg border border-gray-800">
                        <h3 className="text-lg font-medium text-white mb-2">Model Specifications</h3>
                        <ul className="list-disc ml-6 space-y-2 text-gray-400">
                            <li><strong>Task:</strong> Multi-class text classification (Defamation, Hate Speech, Harassment).</li>
                            <li><strong>Architecture:</strong> Transformer-based LLM fine-tuned on legal precedents.</li>
                            <li><strong>Output:</strong> Probability score (0-100%) and categoric classification.</li>
                        </ul>
                    </div>
                </section>

                <section className="mb-16">
                    <h2 className="text-2xl font-semibold text-white mb-4 border-l-4 border-cyan-500 pl-4">
                        3. Cryptographic Preservation (Blockchain Anchoring)
                    </h2>
                    <p className="mb-4">
                        To prevent evidence tampering, ChainForensix generates a <strong>SHA-256 cryptographic hash</strong> of the captured data payload. This hash is then anchored to the destination blockchain network.
                    </p>
                    <p className="mb-4">
                        This process creates an immutable timestamp. Any alteration to the stored evidence file would result in a different hash, alerting the investigator to a breach of integrity.
                    </p>
                    <p className="font-mono text-sm bg-black/50 p-4 rounded text-cyan-400">
                        Evidence Hash: SHA-256(Raw_JSON + Analysis_Report)
                    </p>
                </section>

                <section>
                    <div className="bg-blue-900/20 border border-blue-500/30 p-8 rounded-xl">
                        <h2 className="text-xl font-bold text-blue-400 mb-2">Court Admissibility</h2>
                        <p className="text-gray-300">
                            Reports generated by ChainForensix differ from standard screenshots. By providing the JSON source and a blockchain verification receipt, our evidence meets the standards for <strong>Scientific Evidence</strong> and digital authenticity in many jurisdictions.
                        </p>
                    </div>
                </section>

            </main>

            <footer className="border-t border-gray-800 bg-[#061225] py-12">
                <div className="max-w-7xl mx-auto px-6 text-center text-gray-500">
                    <p>&copy; {new Date().getFullYear()} ChainForensix. All rights reserved.</p>
                </div>
            </footer>
        </div>
    );
};

export default MethodologyPage;
