import React from 'react';
import SEO from './components/SEO';

const TermsPage = () => {
    return (
        <div className="bg-[var(--bg-color)] text-[var(--text-primary)] min-h-screen font-sans py-24 px-6">
            <SEO
                title="Terms of Service"
                description="ChainForensix Terms of Service. User agreement for accessing our digital forensic tools and blockchain anchoring services."
                canonical="https://forensic-tool-project.vercel.app/terms"
            />
            <div className="max-w-4xl mx-auto">
                <h1 className="text-4xl font-heading font-bold mb-8 border-b border-[var(--border-color)] pb-4">Terms of Service</h1>
                <div className="prose prose-lg text-[var(--text-secondary)] leading-relaxed space-y-6">
                    <p>Last updated: January 14, 2026</p>
                    <section>
                        <h2 className="text-2xl font-bold text-[var(--text-primary)] mb-4">1. Acceptance of Terms</h2>
                        <p>By accessing or using ChainForensix, you agree to be bound by these Terms of Service and all applicable laws and regulations.</p>
                    </section>
                    <section>
                        <h2 className="text-2xl font-bold text-[var(--text-primary)] mb-4">2. Use License</h2>
                        <p>Permission is granted to use ChainForensix for personal or professional digital forensic purposes. This is the grant of a license, not a transfer of title.</p>
                    </section>
                    <section>
                        <h2 className="text-2xl font-bold text-[var(--text-primary)] mb-4">3. Disclaimer</h2>
                        <p>The forensic reports generated by ChainForensix are provided "as is". While we strive for absolute accuracy and cryptographic integrity, the legal admissibility of evidence depends on local laws and judicial discretion.</p>
                    </section>
                    <section>
                        <h2 className="text-2xl font-bold text-[var(--text-primary)] mb-4">4. Limitations</h2>
                        <p>In no event shall ChainForensix or its creators be liable for any damages arising out of the use or inability to use the platform.</p>
                    </section>
                </div>
            </div>
        </div>
    );
};

export default TermsPage;
